version: 2

models:
    - name: dim_listings_cleansed
      description: "This model is a cleaned table with airbnb lisitings"
      data_tests:
        - name: minimum_row_count
          test_name: minimum_row_count
          arguments:
            min_row_count: 1000
          config:
            severity: error
      columns:
        - name: listing_id
          description: "The unique identifier for each listing"
          data_tests:
            - not_null
            - unique
    
        - name: host_id
          description: "The unique identifier for each host. References host table"
          data_tests:
            - not_null
            - relationships:
                arguments:
                    to: ref('dim_hosts_cleansed')
                    field: host_id
        - name: room_type
          description: "The type of apartment/room"
          data_tests:
            - accepted_values:
                arguments:
                    values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']  
        - name: minimum_nights
          description: "{{ doc('dim_listing_cleansed__minimum_nights') }}"
          data_tests:
            - positive_values

    - name: dim_hosts_cleansed
      config:                # this block confiures this test to be a contract
        contract:
          enforced: true        # this block confiures this test to be a contract
      constraints:
        - type: primary_key
          columns: [host_id]
      columns:
        - name: host_id
          data_type: integer   # this block confiures this test to be a contract
          constraints:
            - type: not_null
            - type: unique
          data_tests:
            - unique
            - not_null
            - relationships:
                arguments:
                    to: ref('dim_listings_cleansed')
                    field: host_id
        
        - name: is_superhost
          data_type: string   # this block confiures this test to be a contract
          data_tests:
            - accepted_values:
                arguments:
                    values: ['t', 'f']

        - name: host_name
          data_type: string   # this block confiures this test to be a contract
          constraints:
            - type: not_null
          data_tests:
            - not_null
        
        - name: updated_at
          data_type: timestamp   # this block confiures this test to be a contract
          data_tests:
            - not_null

        - name: created_at
          data_type: timestamp    # this block confiures this test to be a contract
          data_tests:
            - not_null
    

    - name: dim_listings_with_hosts
      tests:
          # basically added a test from dbt_expectations package to check if 
          #  the row count of this model is equal to the row count of the source table
        - dbt_expectations.expect_table_row_count_to_equal_other_table: 
            compare_model: source('airbnb', 'listings')
      columns:
        - name: price
          # This test checks if the 99th percentile of the price column is between 50 and 500
          # This is to ensure that the price column does not have any outliers that are too
          tests:
            - dbt_expectations.expect_column_quantile_values_to_be_between:
                quantile: .99
                min_value: 50
                max_value: 500 

            # This test checks for the maximum value of the price column 
            # to be between 1 and 5000 to ensure
            # the config has been set to warn if the test fails instead of failing the build
            - dbt_expectations.expect_column_max_to_be_between:
                min_value: 1 
                max_value: 5000 
                config:
                  severity: warn
            
            # checks that the format of the price column is a number
            - dbt_expectations.expect_column_values_to_be_of_type:
                column_type: number


         